pipeline {

  environment { 
    APP_NAME='hello-world'
    DEV_NAMESPACE='hello-world-dev'
   }

  agent { label 'oc' }

  stages {

  stage('Build') {
    steps {
      script {
      openshift.withCluster() {
	openshift.withProject(env.DEV_NAMESPACE) {

	openshift.newBuild(".", "--name=${env.APP_NAME}", "--image-stream=jboss-webserver31-tomcat8-openshift:1.4", "--context-dir='TestShailendra'")
      }
      }
    }
  }
 }
 stage('Deploy') {
    steps {
      script {
      openshift.withCluster() {
        openshift.withProject(env.DEV_NAMESPACE) {
	openshift.newApp("${env.APP_NAME}:latest", "--name=${env.APP_NAME}").narrow('svc').expose()
          
          }
        }
      }
    }
    }

}
}
