pipeline {

  environment { 
    APP_NAME='hello-world'
    DEV_NAMESPACE='hello-world-dev'
   }

  agent { label 'oc' }

  stages {

  stage('Build') {
    steps {
      script {
      openshift.withCluster() {
	openshift.withProject(env.DEV_NAMESPACE) {

	openshift.newBuild(".", "--name=${env.APP_NAME}", "--docker-image=registry.redhat.io/jboss-webserver-3/webserver31-tomcat8-openshift", "--context-dir='TestShailendra'")
      }
      }
    }
  }
 }

}
}
